version: "3"

services:
  # cache:
  #   image: redis
  #   ports:
  #     - 46379:46379
  #   volumes:
  #   - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   - ./datastore/redis-data/fabricate:/data:rw
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   networks:
  #     - fabricate-network
      
  server: 
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: server
    ports:
      - 28100:28100
    volumes:
      - ./backend:/code
      - ./datastore:/data:rw
    env_file:
      - .env
    networks:
      - fabricate-network
    depends_on:
      # - cache
      - db
  webui:
    build:
      context: .
      dockerfile: ./webui/Dockerfile
    container_name: webui
    ports:
      - 28101:28101
      - 5173:5173
    volumes:
      - ./webui:/code
      - ./datastore:/data:rw
    env_file:
      - .env
    networks:
      - fabricate-network
    depends_on:
      - server
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db:rw
    networks:
      - fabricate-network
networks:
  fabricate-network:
    external: true
  
volumes: 
  mongodata:
