name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Define the directory as an environment variable
    env:
      WORKING_DIRECTORY: ./webui

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './webui/package-lock.json' 
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Build
      run: npm run build --if-present
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Run tests
      run: npm test
      working-directory: ${{ env.WORKING_DIRECTORY }}